# Generated by Django 4.0.10 on 2023-03-24 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_unique_together_task_unique_tasks_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
