# Generated by Django 4.0.10 on 2023-03-21 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ('order',)},
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('board', 'order')},
        ),
    ]
