# Generated by Django 4.0.10 on 2023-03-23 15:10

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_alter_column_options_alter_column_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='column',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('board', 'order'), name='unique_columns_order'),
        ),
    ]
