# Generated by Django 4.0.10 on 2023-03-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_column_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='is_completed_column',
            field=models.BooleanField(default=None, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(fields=('is_completed_column', 'board'), name='unique_completed_column'),
        ),
    ]
