# Generated by Django 4.0.10 on 2023-03-25 23:58

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_column_is_completed_column_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='column',
            name='unique_completed_column',
        ),
        migrations.AddConstraint(
            model_name='column',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('is_completed_column', 'board'), name='unique_completed_column'),
        ),
    ]
